/run/initialize

# Run A: Material only
/mydet/setMagneticField false
/mydet/setMaterialSlab true
/run/initialize
/gun/momentum 1.0
/run/beamOn 100000

# Run B: Magnet only
/mydet/setMagneticField true
/mydet/setMaterialSlab false
/run/initialize
/gun/momentum 1.0
/run/beamOn 100000

# Run C: Hybrid
/mydet/setMagneticField true
/mydet/setMaterialSlab true
/run/initialize
/gun/momentum 1.0
/run/beamOn 100000